apiVersion: v1
kind: ConfigMap
metadata:
  name: unleash-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  UNLEASH_API_URL: "http://unleash.default.svc.cluster.local:4242/api"
  UNLEASH_INSTANCE_ID: "dev-instance"
  UNLEASH_ENABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo.default.svc.cluster.local:27017/demo"
